import 'package:audioplayers/audioplayers.dart';
import 'package:suspecto/core/audio/test_environment.dart';

/// Short bundled effects, generated by scripts/generate_sounds.py.
enum Sfx { tap, reveal, vote, tick, timeup, win, imposters, jester }

/// Plays sound effects. Failures are silent: a missing audio device must
/// never interrupt a game.
class SoundEffects {
  SoundEffects({bool? enabled}) : _enabled = enabled ?? !runningInFlutterTest;

  final bool _enabled;
  final Map<Sfx, AudioPlayer> _players = {};

  Future<void> play(Sfx sfx) async {
    if (!_enabled) {
      return;
    }
    try {
      var player = _players[sfx];
      if (player == null) {
        player = AudioPlayer();
        _players[sfx] = player;
        await player.setReleaseMode(ReleaseMode.stop);
      }
      await player.stop();
      await player.play(AssetSource('sounds/${sfx.name}.wav'),
          mode: PlayerMode.lowLatency);
    } catch (_) {/* Sound is optional. */}
  }

  Future<void> dispose() async {
    for (final player in _players.values) {
      try {
        await player.dispose();
      } catch (_) {}
    }
    _players.clear();
  }
}
