"""Validate multilingual packs and generate offline Dart constants. No network."""
import ast
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LANGUAGES = ('en', 'ar', 'es', 'fr', 'ja', 'zh-Hans', 'zh-Hant')


def validate_words(rows):
    seen = {key: set() for key in ('id', *LANGUAGES)}
    for row in rows:
        for field in ('id', 'category', *LANGUAGES):
            if not isinstance(row.get(field), str) or not row[field].strip():
                raise ValueError(f'Invalid {field}: {row.get("id")}')
        if type(row.get('difficulty')) is not int or row['difficulty'] not in (1, 2, 3):
            raise ValueError(f'Invalid difficulty: {row["id"]}')
        for key, values in seen.items():
            value = row[key].strip().casefold()
            if value in values:
                raise ValueError(f'Duplicate {key}: {row[key]}')
            values.add(value)


def validate_ui(catalogs, required):
    for language in LANGUAGES[2:]:
        catalog = catalogs.get(language)
        if not isinstance(catalog, dict) or set(catalog) != required:
            raise ValueError(f'Incomplete UI catalog: {language}')
        for source, translated in catalog.items():
            if not isinstance(translated, str) or not translated.strip():
                raise ValueError(f'Empty UI translation: {language}: {source}')
            if sorted(re.findall(r'\{\w+\}', source)) != sorted(re.findall(r'\{\w+\}', translated)):
                raise ValueError(f'Placeholder mismatch: {language}: {source}')


def dart(value):
    return "'" + value.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$').replace('\n', '\\n').replace('\r', '\\r') + "'"


def main():
    rows = json.loads((ROOT / 'assets/content/words.json').read_text())['words']
    validate_words(rows)
    source = (ROOT / 'lib/core/localization.dart').read_text()
    arabic = source.split('const _arabic =')[1]
    required = {ast.literal_eval("'" + key + "'") for key in
                re.findall(r"'((?:\\.|[^'\\])*)'\s*:", arabic)}
    templates = source.split('final _dynamicMessages =')[1].split('class LocalText')[0]
    required.update(ast.literal_eval("'" + key + "'") for key in
                    re.findall(r",\s*'((?:\\.|[^'\\])*)'\s*,\s*\[", templates))
    catalogs = json.loads((ROOT / 'assets/content/ui_translations.json').read_text())
    validate_ui(catalogs, required)
    header = '// Generated by scripts/generate_content.py. Edit assets/content files.\n'
    content = header + "import 'package:suspecto/features/game/domain/models/word_entry.dart';\n\nconst starterWords = <WordEntry>[\n"
    for row in rows:
        content += f"  WordEntry(value: {dart(row['en'])}, category: {dart(row['category'])}, difficulty: {row['difficulty']}),\n"
    (ROOT / 'lib/features/game/data/local/starter_words.dart').write_text(content + '];\n')
    words = header + 'const wordTranslations = <String, Map<String, String>>{\n'
    for language in LANGUAGES[1:]:
        words += f'  {dart(language)}: {{\n'
        for row in rows:
            words += f"    {dart(row['en'])}: {dart(row[language])},\n"
        words += '  },\n'
    words += '};\nfinal arabicWords = wordTranslations[\'ar\']!;\n'
    (ROOT / 'lib/features/game/data/local/word_translations.dart').write_text(words)
    ui = header + 'const uiTranslations = <String, Map<String, String>>{\n'
    for language, catalog in catalogs.items():
        ui += f'  {dart(language)}: {{\n'
        for source, translated in catalog.items():
            ui += f'    {dart(source)}: {dart(translated)},\n'
        ui += '  },\n'
    (ROOT / 'lib/core/ui_translations.dart').write_text(ui + '};\n')
    print(f'Validated {len(rows)} unique words in {len(LANGUAGES)} locales and {len(required)} UI messages per new locale.')


if __name__ == '__main__':
    main()
