"""Validate bilingual packs and generate offline Dart constants. No network needed."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
rows = json.loads((root / 'assets/content/words.json').read_text())['words']
ids, english, arabic = set(), set(), set()
for row in rows:
    for field in ['id', 'category', 'en', 'ar']:
        if not isinstance(row[field], str) or not row[field].strip():
            raise ValueError(f'Invalid {field}: {row}')
    for key, seen in [('id', ids), ('en', english), ('ar', arabic)]:
        normalized = row[key].strip().casefold()
        if normalized in seen:
            raise ValueError(f'Duplicate {key}: {row[key]}')
        seen.add(normalized)

def dart(value):
    return "'" + value.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$') + "'"

content = "// Generated by scripts/generate_content.py. Edit assets/content/words.json.\nimport 'package:suspecto/features/game/domain/models/word_entry.dart';\n\nconst starterWords = <WordEntry>[\n"
for row in rows:
    content += f"  WordEntry(value: {dart(row['en'])}, category: {dart(row['category'])}, difficulty: {row['difficulty']}),\n"
(root / 'lib/features/game/data/local/starter_words.dart').write_text(content + '];\n')
translations = '// Generated by scripts/generate_content.py.\nconst arabicWords = <String, String>{\n'
for row in rows:
    translations += f"  {dart(row['en'])}: {dart(row['ar'])},\n"
(root / 'lib/features/game/data/local/word_translations.dart').write_text(translations + '};\n')
print(f'Validated {len(rows)} unique bilingual words in {len({r["category"] for r in rows})} categories.')
